### ISSUE TITLE
Error: Cannot find module './build/Release/wm'

### ISSUE THREAD

**Issue by miliu99** [yvesh/active-windows#3]
I just tried it out on Windows 10, and got this error right away. Any idea?

I'm using electron 8.2.1.

**Comment by yvesh** [comment]
How are you building it? You need to compile it (npm-gyp) or use the prebuilt package. When you add it as dependency `npm / yarn install` should normally trigger the compiling.

**Comment by miliu99** [comment]
Interesting...I tried it again and it works this time. I don't know what I did wrong last time. Thank you very much!

**Comment by yvesh** [comment]
Weird, but glad it's working now.

**Comment by t-morisawa** [comment]
When I installed with save-dev, I got the same error; when I installed without save-dev, it worked correctly.
