### ISSUE TITLE
Build fails on linux

### ISSUE THREAD

**Issue by blockchain-expert** [yvesh/active-windows#7]
When I install this module on linux, the build fails.

`prebuild-install WARN install No prebuilt binaries found (target=10.16.3 runtime=node arch=x64 libc= platform=linux)`

**Comment by yvesh** [comment]
That's not a fail, that's just a warning that there is no prebuilt binary for your node / linux version. 

When there is no prebuilt package, the package should build after that line with node-gyp. Maybe you are missing some build dependencies? Any output afterwards?

**Comment by blockchain-expert** [comment]
Yes.

`g++: error: Time: No such file or directory
g++: error: nodeApp/node_modules/active-windows/node_modules/node-addon-api: No such file or directory
wm.target.mk:115: recipe for target 'Release/obj.target/wm/cppsrc/main.o' failed
make: *** [Release/obj.target/wm/cppsrc/main.o] Error 1`

**Comment by yvesh** [comment]
You need to install the compiler (g++) to build the module (and probably the other dev requirements too) :-)
